apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only-cluster-role
  namespace: default
rules:
  - verbs:
    - "list"
    apiGroups:
    - ""
    resources:
    - pods
