apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      type: dev
  template:
    metadata:
      name: nginx-pod
      labels:
        type: dev
    spec:
      containers:
        - name: nginx
          image: nginx

      