apiVersion: v1
kind: Pod
metadata:
  name: default-pod
  namespace: default
spec:
  containers:
  - name: golang
    image: golang:latest
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10

  