apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev
spec:
  containers:
  - name : nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: redis-db
    image: redis:latest
    ports:
    - containerPort: 6379
