apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rs
  labels:
    app: myapp
    type: dev
spec:
 replicas: 2
 selector:
   app: myapp
 template:
   metadata:
     labels:
       name: myapp-pod
       app: myapp
       type: dev
   spec:
      containers:
      - name: nginx-container
        image: nginx
   